// do not edit this file

import script from './assets/_js/main';
import style from './assets/_scss/main.scss';

function importAll(r) {
  return r.keys().map(r);
}

const images = importAll(require.context('./assets/img/', true, /\.(png|jpe?g|svg)$/));
const media = importAll(require.context('./media/', true, /\.(png|jpe?g|svg)$/));